# Site settings
title: HUCO&CO, BENJAMIN.company 
email: benjamin.kim@humancoding.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://humancoding.com" # the base hostname & protocol for your site

twitter_username: huconco
github_username:  huconco

# Build settings
# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

highlighter: pygments
permalink: pretty

safe: true
lsi: true

gems:
  - jekyll-redirect-from
  - jemoji
